(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var O0=function(a){a.V("cardstatechange",a.Gh()&&a.pk()?1:0)},P0=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},SEa=function(a){var b=g.ng(a);
a=g.tg(a);return new g.Uf(b.x,b.y,a.width,a.height)},TEa=function(a){return Math.pow(a,3)},UEa=function(a){return 3*a*a-2*a*a*a},S0=function(a){a=g.Qa(a);
delete Q0[a];g.Qb(Q0)&&R0&&R0.stop()},WEa=function(){R0||(R0=new g.J(function(){VEa()},20));
var a=R0;a.isActive()||a.start()},VEa=function(){var a=g.Ta();
g.Bb(Q0,function(b){XEa(b,a)});
g.Qb(Q0)||WEa()},T0=function(a,b,c,d){g.mn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.I=0;this.B=null},XEa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.B);a.B=b;YEa(a,a.progress);1==a.progress?(a.Za=0,S0(a),a.onFinish(),a.tu()):a.kc()&&a.mz()},YEa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},ZEa=function(a,b){g.zl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Za},U0=function(a,b,c,d,e){T0.call(this,b,c,d,e);
this.element=a},V0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
U0.call(this,a,b,c,d,e)},W0=function(a){g.F.call(this);
this.l=a||window;this.i=[]},X0=function(a){return a.baseUrl||null},Y0=function(a,b){return g.Ie(g.Oc(a,b,void 0),function(c){return!!c})},$Ea=function(a,b,c){function d(ka){var Cb,qc,pe,Ca=ka.hovercardButton;
if(!Ca)return null;Ca=Ca.subscribeButtonRenderer;if(!Ca)return null;var Wd=f(Ca.unsubscribedButtonText),rh=f(Ca.subscribedButtonText);if(Ca.subscribed){var ml=f(Ca.subscriberCountWithUnsubscribeText);var Bj=f(Ca.subscriberCountText)}else ml=f(Ca.subscriberCountText),Bj=f(Ca.subscriberCountWithSubscribeText);var ef=null;return ka.signinEndpoint&&(ef=P0(ka,"signinEndpoint","webNavigationEndpointData","url"),ef||(ef=null===(pe=null===(qc=null===(Cb=Ca.signInEndpoint)||void 0===Cb?void 0:Cb.commandMetadata)||
void 0===qc?void 0:qc.webCommandMetadata)||void 0===pe?void 0:pe.url),!ef)?null:Wd&&(rh||ef)?{subscribed:Ca.subscribed,subscribeText:Wd,subscribeCount:ml,unsubscribeText:rh,unsubscribeCount:Bj,enabled:Ca.enabled,signinUrl:ef,classic:ka.useClassicSubscribeButton}:null}
function e(ka){if(ka){var Cb=[],qc=ka.videoId;qc&&Cb.push("v="+qc);(qc=ka.playlistId)&&Cb.push("list="+qc);(ka=ka.startTimeSeconds)&&Cb.push("t="+ka);return"/watch?"+Cb.join("&")}}
function f(ka){if(!ka)return null;var Cb=ka.simpleText;return Cb?Cb:ka.runs?g.Oc(ka.runs,function(qc){return qc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,E=null,D=null,G=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=P0(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):E=f(b.subscribersText)}else"WEBSITE"===
h?((D=P0(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=P0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=P0(b,"title","accessibility","accessibilityData","label");var T=b.endpoint?b.endpoint.clickTrackingParams:null,ta="";if(b.metadata){var Ba=f(b.metadata);Ba&&(ta=Ba)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ta,callToAction:f(b.callToAction),
eG:b.image,iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:E,isSubscribe:x,targetUrl:m||null,RO:n,ge:T?{itct:T}:null,uT:p,Gs:a?a:null,UO:b.isPlaceholder,impressionUrls:Y0(b.impressionUrls||[],X0),KO:Y0(b.hovercardShowUrls||[],X0),clickUrls:Y0(l.loggingUrls||[],X0),visualElement:g.ku(b.trackingParams),
productPrice:G,additionalFeesText:I}},Z0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Y0(a.impressionUrls||[],X0),elements:Y0(a.elements||[],function(d,e){return $Ea(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ku(a.trackingParams));return c},$0=function(a){g.hM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.L=g.KD(a)||g.ND(a);this.events=new g.$L(this);g.H(this,this.events);this.events.N(this.player,g.rB("creatorendscreen"),this.Yd);this.events.N(this.player,g.sB("creatorendscreen"),this.ag);this.events.N(this.player,"resize",this.tb);this.events.N(window,"focus",this.yS);this.load();var b=g.De("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.wi(this,function(){g.He(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},aFa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},a1=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},bFa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Z0(f,aFa(a))));b1(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.Wn;d&&(c.postParams={ad_tracking:d});if(b=g.SG(b))if(b=g.Jc(b),b=g.Ec(b))a.u=g.Xp(b,c)},b1=function(a,b,c){c=void 0===c?!0:c;
a.player.Df("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&cFa(a);c=[];d=new g.oB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",K:"ytp-ce-shadow"}),g.YL(a.player,a.l.element,4),a.B=new g.OK(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=dFa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.YL(a.player,f.element,4);var h=new g.oB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);eFa(a,f,e)}else g.nt(new g.Zr("buildEndscreenElement null",
e))}a.player.Sd(c);a.tb()}},cFa=function(a){var b=g.ou(),c=g.qu();
c&&b&&a.endscreen.visualElement&&g.Eu(c,b,a.endscreen.visualElement)},dFa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.ea("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ba:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Gs||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:c1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:d1(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ba:["ytp-ce-video-title"].concat(g.ma(c)),U:{dir:g.sn(b.title||
"")},ma:b.title},{D:"div",K:"ytp-ce-video-duration",ma:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.ea("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Gs||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:c1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:d1(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ba:["ytp-ce-playlist-title"].concat(g.ma(c)),U:{dir:g.sn(b.title||"")},ma:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ma:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Gs||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],U:{href:d1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.sn(b.title||"")},ma:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ma:b.subscribersText}:"",b.metadata?{D:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ma:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:c1(b)}]};c=new g.V(c);var d=g.me(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.ge.itct}else e="endscreen",f=null;e=new g.iN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ba:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Gs||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.sn(b.title||"")},ma:b.title},{D:"div",K:"ytp-ce-website-metadata",ma:b.metadata},{D:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],U:{href:d1(a,b.targetUrl),target:"_blank",tabindex:"-1"},ma:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:c1(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:fFa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ma:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ma:b.additionalFeesText})),a={D:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Gs||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.sn(b.title||"")},ma:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ma:b.metadata},{D:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:d1(a,b.targetUrl),target:"_blank",tabindex:"-1"},ma:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:c1(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ma:b.callToAction||void 0}]}]},c=new g.V(a)}b.UO&&g.K(c.element,"ytp-ce-placeholder");return c},c1=function(a){if(a.eG)var b=a.eG.thumbnails;
return fFa(b?b[b.length-1].url:null)},fFa=function(a){return a?{style:"background-image: url("+a+")"}:{}},eFa=function(a,b,c){function d(m){m&&(b.Na("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.K(b.element,"ytp-ce-force-expand"),e1(a,c.id,!0)):(g.jn(b.element,"ytp-ce-force-expand"),g.jn(b.element,"ytp-ce-element-hover"),e1(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Na("mouseenter",function(){f1(a,b,c)});
b.Na("mouseleave",function(){g1(a,b,c)});
a.player.T().i||b.Na("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Na("click",function(m){gFa(a,c,m)});
b.Na("keypress",function(m){gFa(a,c,m)});
b.Na("focus",function(){f1(a,b,c)});
b.Na("blur",function(){g1(a,b,c)});
b.Na("touchstart",function(){f1(a,b,c)});
var l=g.oe("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.jn(b.element,"ytp-ce-element-hover");g.jn(b.element,"ytp-ce-force-expand")});
b.Na("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.oe("ytp-sb-subscribe",b.element));d(g.oe("ytp-sb-unsubscribe",b.element));b.Na("focus",f);b.Na("blur",h)},gFa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.gn(d,"ytp-ce-element");){g.gn(d,"subscribe-label")&&h1(a,b);
if(g.gn(d,"ytp-ce-channel-subscribe"))return;d=g.Je(d)}if(!d||g.gn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])g1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.uT)h1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jc(d1(a,b.targetUrl)),c=g.Ec(c),g.LI(c,void 0,b.ge);else{var e=a.player.getVideoData().C,f=function(){var h=d1(a,b.targetUrl),l=b.ge,m=g.Gp(h);e&&m&&(m.v||m.list)?a.player.Mj(m.v,l,m.list,!1):g.KI(h,l)};
h1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},d1=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.EE(a)+b}else return"";return b},f1=function(a,b,c){g.gn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),i1(a,c.KO),e1(a,c.id,!0))},g1=function(a,b,c){g.jn(b.element,"ytp-ce-element-hover");
g.jn(b.element,"ytp-ce-force-expand");e1(a,c.id,!1)},e1=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.L(a.i[e].element,"ytp-ce-element-shadow-show",c)},i1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||a1(a))c&&c();else{b=hFa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.sq(b[a],d)}},h1=function(a,b,c){i1(a,b.clickUrls,c);
(a=g.qu())&&b.RO&&g.Hu(a,b.visualElement)},hFa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(iFa(b[d],c));return a},iFa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},jFa=function(a){return Array.isArray(a)&&a.length?a[0]:a},j1=function(a){return"string"===typeof a?a:""},k1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},kFa=function(a){this.externalId=a},lFa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},l1=function(a){return a.value?a.value:null},m1=function(a){if(!a)return null;
var b=g.Jc(j1(a.value));b=g.Ec(b);if(!b)return null;var c=k1(a.target,mFa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new lFa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},nFa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},qFa=function(a){if(!a)return null;
var b=k1(a.type,oFa),c=k1(a.trigger,pFa),d=jFa(a.url);d=m1(d?d:null);a=jFa(a.subscribeData);var e=a?a:null;e?(a=j1(e.external_user_id),e=j1(e.subscription_token),a=a&&e?new kFa(a):null):a=null;return b?new nFa(b,c,d,a):null},rFa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},tFa=function(a){return(a=sFa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},sFa=function(a,b){return g.cb(a.action,b,void 0)},uFa=function(a,b){this.context=a;
this.i=b},o1=function(a){return a.customMessage?n1("div","iv-card-message",a.customMessage):""},p1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},S:c}},q1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(n1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},n1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.sn(c);return{D:a,U:b,ma:c}},vFa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Ov&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Ov+");");c.dir=g.sn(a.customMessage);var d=[{D:"span",ma:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ba:b,U:c,S:d}},r1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.ge,c.tracking.click,5)}},wFa=function(a,b){this.merchant=a;
this.price=b},xFa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},yFa=function(a,b){return b?b:xFa(a)?"current":"new"},s1=function(a,b){g.F.call(this);
var c=this;this.element=a;this.context=b;this.Ya=!1;this.Ma=new Map;this.Qa=new Map;this.context.G.addEventListener(g.rB("annotations_module"),function(d){(d=c.Ma.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.sB("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)})},t1=function(a,b,c,d,e,f,h){a.context.i.Na(b,"click",function(l){a.nz(c,d,e,f||[],h||0,l)});
a.context.i.Na(b,"touchstart",function(){a.Ya=!1});
a.context.i.Na(b,"touchmove",function(){a.Ya=!0})},zFa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},u1=function(a,b,c){return{YG:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
ZJ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
dy:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},x1=function(a,b,c){s1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Da=this.ub=this.u=this.Le=!1;this.ra=null;this.cards=[];this.gb=this.L=this.Aa=this.C=this.Fa=this.i=null;this.X=[];this.J=this.Ee=this.Ca=null;this.I=0;this.va=new g.J(g.Ka,c.B.kd?4E3:3E3);g.H(this,this.va);this.Va=new g.J(g.Ka);g.H(this,this.Va);this.Y=new uFa(c,function(e,f,h,l,m,n){t1(d,e,f,h,l,m,n)});
this.W=new g.V({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ba:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.H(this,this.W);this.B=this.W.element;this.Wa=new g.OK(this.W,330);g.H(this,this.Wa);this.qb=g.oe("iv-drawer-header-text",this.B);this.l=g.oe("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.ub&&v1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ub=d.u)&&w1(d)})},AFa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){v1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){w1(a)});
var c=b.headerText;g.Ne(a.qb,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.ku(b.trackingParams);a.J=g.ku(b.closeTrackingParams);a.Ee=g.ku(b.iconTrackingParams)},BFa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.yB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,ge:y1(a,c,b,d),sponsored:!1,tracking:u1(d,e,d.command),vl:d.trackingParams?g.ku(d.trackingParams):null,Oi:e.trackingParams?
g.ku(e.trackingParams):null,Ee:f&&f.trackingParams?g.ku(f.trackingParams):null,imageUrl:z1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.yB(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Ov:null,title:d.title?g.yB(d.title):"",customMessage:d.callToAction?g.yB(d.callToAction):"",url:d.command.urlEndpoint.url?m1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};A1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.yB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,ge:y1(a,c,b,d),sponsored:!1,tracking:u1(d,e,d.endpoint),vl:d.trackingParams?g.ku(d.trackingParams):null,Oi:e.trackingParams?g.ku(e.trackingParams):null,Ee:f&&f.trackingParams?g.ku(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.yB(d.customText):null,kJ:z1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.yB(d.channelName):"",metaInfo:[d.subscriberCountText?g.yB(d.subscriberCountText):""],url:m1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};A1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.yB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,ge:y1(a,c,b,d),sponsored:!1,tracking:u1(d,e,d.action),vl:d.trackingParams?g.ku(d.trackingParams):null,Oi:e.trackingParams?g.ku(e.trackingParams):null,Ee:f&&f.trackingParams?g.ku(f.trackingParams):
null,Yu:z1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.yB(d.customMessage):null,playlistVideoCount:g.yB(d.playlistVideoCount),title:d.playlistTitle?g.yB(d.playlistTitle):"",metaInfo:[d.channelName?g.yB(d.channelName):"",d.videoCountText?g.yB(d.videoCountText):""],url:m1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:zFa(d.action)})};A1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.yB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,ge:y1(a,c,b,d),sponsored:!1,tracking:u1(d,e,d.action),vl:d.trackingParams?g.ku(d.trackingParams):null,Oi:e.trackingParams?g.ku(e.trackingParams):null,Ee:f&&f.trackingParams?g.ku(f.trackingParams):null,Yu:z1(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.yB(d.lengthString):null,customMessage:d.customMessage?g.yB(d.customMessage):null,title:d.videoTitle?g.yB(d.videoTitle):"",metaInfo:[d.channelName?g.yB(d.channelName):"",d.viewCountText?g.yB(d.viewCountText):""],isLiveNow:!!d.badge,url:m1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:zFa(d.action)})};A1(a,b)}a.I++},z1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},y1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},DFa=function(a,b){if(b=CFa(a,b))b===a.i&&(a.i=null),a.G.removeCueRange(b.card.id),g.He(b.Tz),g.kb(a.cards,b),a.Qv(),B1(a)},v1=function(a,b,c){if(!a.u){a.Wa.show();
a.Fa=new g.J(function(){g.K(a.context.G.getRootNode(),g.aS.IV_DRAWER_OPEN)},0);
a.Fa.start();a.ra=g.ap(a.l,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.qu();d&&a.Ca&&a.J&&g.Fu(d,[a.Ca,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.CH||(f.CH=!0,EFa(a.context.logger,f.card.tracking.YG,b)),d&&g.Fu(d,[f.card.vl]);O0(a.G);c&&(a.C=new g.J(function(){a.Aa=a.L;a.gb.focus()},330),a.C.start())}},w1=function(a){a.u&&(a.Wa.hide(),g.bp(a.ra),a.ra=null,g.jn(a.context.G.getRootNode(),g.aS.IV_DRAWER_OPEN),a.u=!1,O0(a.G),a.C&&a.C.stop(),a.C=new g.J(function(){a.Aa&&(a.Aa.focus(),a.Aa=null)},330),a.C.start())},
GFa=function(a){g.hn(a.element,[g.aS.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.YL(a.G,a.B,5);FFa(a);a.L=g.oe("ytp-cards-button",a.G.getRootNode());a.gb=g.oe("iv-drawer-close-button",a.B);a.Le=!0},FFa=function(a){var b=g.oe("iv-drawer-close-button",a.B);
a.context.i.Na(b,"click",a.BN,a);a.context.i.Na(a.l,"touchend",function(){a.va.start()});
a.context.i.Na(a.l,"scroll",a.NN,a);a.context.l.subscribe("onHideControls",function(){a.Da=!0});
a.context.l.subscribe("onShowControls",function(){a.Da=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Da=g.gn(a.G.getRootNode(),"ytp-autohide")});
a.X.push(g.Go("iv-button-shown",a.ZO,a));a.X.push(g.Go("iv-button-hidden",a.YO,a));a.X.push(g.Go("iv-teaser-shown",a.bM,a));a.X.push(g.Go("iv-teaser-hidden",a.bP,a));a.X.push(g.Go("iv-teaser-clicked",a.aM,a))},A1=function(a,b){a.Le||GFa(a);
DFa(a,b.id);var c=HFa(a,b);if(c){var d={card:b,Tz:c.element,CH:!1},e=IFa(a,d);g.rb(a.cards,e,0,d);c.xa(a.l,e);a.Qv();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,B1(a),JFa(a,d),v1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&KFa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){KFa(a,d)}),B1(a))}},HFa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",ma:b.displayDomain}:void 0;var d=vFa(b);c={D:"div",Ba:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?l1(b.url)||"":""},S:[p1(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[n1("h2",void 0,b.title),d]}]}]};c=new g.V(c);r1(a,g.ne("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Ba:["iv-card","iv-card-channel"],S:[{D:"a",Ba:["iv-click-target"],U:{href:l1(b.url)||"","data-ytid":b.channelId},S:[p1(b.kJ),
{D:"div",K:"iv-card-content",S:[o1(b),{D:"h2",K:"iv-card-primary-link",ma:b.title},q1(b)]}]}]},c=new g.V(c),r1(a,g.ne("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Ba:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:l1(b.url)||""},S:[p1(b.Yu,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ma:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[o1(b),n1("h2","iv-card-primary-link",b.title),q1(b)]}]}]},c=new g.V(c),
r1(a,g.ne("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.gb(b.offers);c=["iv-card"];d="";var f=vFa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",ma:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",ma:f.merchant}),f={D:"div",S:e});e=b.url?l1(b.url)||"":"";c={D:"div",Ba:c,U:{tabindex:"0"},S:[{D:"a",Ba:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ma:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},S:[n1("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.De("span");g.Ne(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Yc(d,"adInfo");r1(a,g.ne("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",ma:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ba:["yt-badge","yt-badge-live"],ma:"LIVE NOW"}:null,d={D:"div",Ba:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:l1(c))||""},S:[p1(b.Yu,d),{D:"div",K:"iv-card-content",S:[o1(b),n1("h2","iv-card-primary-link",b.title),q1(b),f]}]}]},c=new g.V(d),
r1(a,g.ne("iv-click-target",c.element),b,b.url),c;default:return null}},IFa=function(a,b){if(0===a.cards.length)return 0;
a=g.db(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},LFa=function(a){return a.i?"productListing"===a.i.card.type:g.Xg(a.cards,function(b){return"productListing"===b.card.type})},B1=function(a){g.L(a.G.getRootNode(),"ytp-cards-shopping-active",LFa(a))},KFa=function(a,b){if(!g.gn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.qu(),d=a.i?a.i.card.Ee:a.Ee;
c&&d&&g.Gu(c,[d]);a.i=b;B1(a)}if(c="none"!=a.element.style.display)g.P(a.context.G.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.G.getPresentingPlayerType()?(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.G.getAdState();c&&b.card.teaserDurationMs&&a.G.Kr(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Va.isActive()||((!a.u||!a.va.isActive()&&a.Da)&&JFa(a,b),a.Va.start(910+b.card.teaserDurationMs))}},
JFa=function(a,b){a.W.vb?(b=new T0([0,
a.l.scrollTop],[0,b.Tz.offsetTop],600,UEa),a.context.u.Na(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Na(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.aK(a.W,!0),a.l.scrollTop=b.Tz.offsetTop,g.aK(a.W,!1))},C1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},CFa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},D1=function(a,b,c){s1.call(this,a,b);
this.annotation=c;this.isActive=!1},MFa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},E1=function(a,b,c){D1.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},NFa=function(a,b){var c=void 0===c?0:c;
var d=SEa(b).width;g.lg(b,d);c=new V0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,TEa);g.H(a,c);a.context.u.Na(c,"begin",function(){g.ug(b,!0)});
c.play()},QFa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ba:["iv-branding-context-name"],ma:b.channel_name}),d=a.createElement({D:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.iN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.i.xa(d));var f=a.createElement({D:"div",Ba:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ba:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.ug(h,!1);var l=a.createElement({D:"div",Ba:["branding-context-container-outer"]});l.appendChild(h);g.dg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){OFa(a,h,l)},500);
g.H(a,a.u);a.context.i.Na(a.element,"mouseover",function(){PFa(a,h,l,f,b.image_height)});
a.context.i.Na(a.element,"mouseout",function(){a.u.start()})}},PFa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.tg(b);a.i||(b.style.width=g.kg(f.width,!0),c.style.width=g.kg(f.width,!0));g.dg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.dg(d,"right","1px");a.B=!0;g.ug(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},OFa=function(a,b,c){g.jn(a.element,"iv-branding-active");
a.I=new g.J(function(){g.ug(b,!1);a.i||(c.style.width=g.kg(0,!0))},250);
a.I.start();a.B=!1},RFa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.l=h},F1=function(a,b,c){D1.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.W=!1;this.I=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ba:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.ug(d.u,!1);g.ug(d.l,!0)},700,this);
g.H(this,this.C)},SFa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=tFa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ma:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ma:b.playlist_length.toString()}),h.appendChild(f));e&&t1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.hd(f,l1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ma:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ma:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ba:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ma:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&t1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&t1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ma:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ma:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ba:["yt-badge","iv-promo-badge-live"],ma:"LIVE NOW"})),g.K(a.i,"iv-click-target"),e&&t1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ba:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.Na(a.l,"click",function(r){G1(a,5E3,r)});
c.appendChild(a.l);g.ug(a.l,!1);a.context.i.Na(a.element,"mouseover",a.sO,a);a.context.i.Na(a.element,"mouseout",a.rO,a);a.context.i.Na(a.element,"touchend",function(r){G1(a,5E3,r)});
a.u=a.createElement({D:"button",Ba:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.Na(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.mO:a.lO,a);c.appendChild(a.u);g.hn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},G1=function(a,b,c){c.stopPropagation();
TFa(a);UFa(a,b);a.i.focus()},VFa=function(a){a.isCollapsed||a.L||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},TFa=function(a){a.C.stop();
a.isCollapsed&&(g.kn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.ug(a.l,!1),g.ug(a.u,!0))},UFa=function(a,b){a.B||(a.B=g.Dm(function(){H1(this);
VFa(this)},b,a))},H1=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},WFa=function(a){this.G=a},EFa=function(a,b,c){b&&(c?I1(a,b.map(function(d){return g.Xm(d,c)})):I1(a,b))},I1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.sq(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},J1=function(a){g.hM.call(this,a);
var b=this;this.W=!1;this.loadNumber=0;this.J={};this.logger=new WFa(this.player);this.C=new g.$L(this);this.I=this.u=null;this.events=new g.$L(this);this.L=this.i=null;this.X=[];g.H(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.V("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.V("onShowControls")});
this.C.N(this.player,"resize",function(d){b.V("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.cM,this);this.subscribe("resize",this.xx,this);this.player.T().L.subscribe("vast_info_card_add",this.YI,this);g.H(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.V({D:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.l);g.YL(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ba:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Jp()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.wi(this,function(){g.He(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},XFa=function(a){a=a.createElement({D:"div",
Ba:["annotation","annotation-type-custom"]});g.ug(a,!1);return a},YFa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.aK(a.l,b);g.aK(a.B,b)},ZFa=function(a,b,c){a.W=!0;
a.I=g.Xp(b,c)},$Fa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push($Fa(a,e))}return c},cGa=function(a){var b=a.player.getVideoData();
if(b.ra){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Sp(h)&&h.responseXML?h.responseXML:null)&&K1(a,h)}};
g.rp()&&(d.onFinish=aGa(a,d.onFinish));d.postParams={ic_only:"1"};bGa(d,c);a.W=!0;g.Xp(b.ra,d)}}},bGa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Qs&&(a.postParams.ic_coll=b.Qs);b.Uv&&(a.postParams.ic_xml=b.Uv);b.ev&&(a.postParams.ic_track=b.ev)},dGa=function(a){var b=new g.V({D:"div"});
g.ug(b.element,!1);var c=new x1(a.player,b.element,L1(a));g.H(c,b);b.xa(a.l.element);c.Nu();return c},L1=function(a){if(!a.L){var b=new W0(a);
g.H(a,b);var c=new g.B_(a);g.H(a,c);a.L=new RFa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Ae)}return a.L},K1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.qu();if(e){var f=g.ou();f&&g.xu(g.Po("use_default_events_client")?void 0:g.ft,e,f,[g.ku(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=$Fa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=k1(f.type,eGa),p=k1(f.style,fGa),r=j1(f.data),t=0!==r.length?JSON.parse(r):{};var w=f.action;f=qFa;if(null==w)var x=null;else if(g.Na(w)){l=[];for(var y=g.q(w),E=y.next();!E.done;E=
y.next()){var D=f(E.value);D&&l.push(D)}x=l}else{var G=f(w);x=G?[G]:[]}e=m&&n?new rFa(m,n,p,x,t):null}else e=null}catch(Cb){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=XFa(f),T=null;switch(l.type){case "branding":if(f.player.T().Ob)break;f.l.element.appendChild(I);T=new E1(I,L1(f),l);break;case "promotion":g.YL(f.player,I,4),T=new F1(I,L1(f),l)}T&&T.Nu();if(f=T)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=dGa(a),g.H(a,a.i));if("card"===e.type){c=
a.i;var ta=e&&e.data&&e.data.card_type;f=e.data;if(ta)switch(l=f.tracking||{},l={YG:l.impression,click:l.click,close:l.close,ZJ:l.teaser_impression,dy:l.teaser_click},I=f.tracking_params||{},T=null,ta){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,ge:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.ku(I.card):null,Oi:I.teaser?g.ku(I.teaser):null,
Ee:I.icon?g.ku(I.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,kJ:f.image_url,title:f.title,metaInfo:f.meta_info,url:m1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};A1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,ge:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?
g.ku(I.card):null,Oi:I.teaser?g.ku(I.teaser):null,Ee:I.icon?g.ku(I.icon):null,Yu:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:m1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};A1(c,e);break;case "productListing":f.signin_url&&(T=m1({target:"current",value:f.signin_url}));ta=[];for(var Ba=f.offers||[],ka=0;ka<Ba.length;ka++)ta.push(new wFa(g.od(Ba[ka].merchant),g.od(Ba[ka].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,ge:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.ku(I.card):null,Oi:I.teaser?g.ku(I.teaser):null,Ee:I.icon?g.ku(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Ov:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:m1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),J6:T,I6:f.signin_title?f.signin_title:void 0,H6:f.signin_message?f.signin_message:void 0,offers:ta};A1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,ge:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.ku(I.card):null,Oi:I.teaser?g.ku(I.teaser):
null,Ee:I.icon?g.ku(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Ov:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:m1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};A1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,ge:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,vl:I.card?g.ku(I.card):null,Oi:I.teaser?g.ku(I.teaser):null,Ee:I.icon?g.ku(I.icon):null,Yu:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:m1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},A1(c,e)}}else AFa(a.i,e);c=!0}}c&&(O0(a.player),a.xx())},gGa=function(a,b){var c=!1;
a.i||(a.i=dGa(a),g.H(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(BFa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.yB(b.headerText):"",g.Ne(c.qb,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.ku(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.ku(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ee=b.icon.infoCardIconRenderer.trackingParams?
g.ku(b.icon.infoCardIconRenderer.trackingParams):null,O0(a.player),a.xx())},hGa=function(a,b,c,d,e){if(!a.player.T().Ob){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new nFa("openUrl","click",new lFa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.yB(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.yB(b.subscriberCountText))):(b.subscriberCountText&&(e=g.yB(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.yB(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.yB(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.yB(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new rFa(c,"branding","branding",f,d);l=XFa(a);a.l.element.appendChild(l);f=new E1(l,L1(a),f);f.Nu();g.H(f,f);a.J[c]=f}},aGa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||(d.unshift(b),b=g.Ra.apply(window,d),a.X.push(g.pp(b)))}},iGa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.RL.prototype.Kr=g.ca(15,function(a,b){var c=g.sM(this.kb());c&&c.Kr(a,b)});
var Q0={},R0=null;g.Ua(T0,g.mn);g.k=T0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Za)this.progress=0,this.coords=this.i;else if(this.kc())return!1;S0(this);this.startTime=a=g.Ta();-1==this.Za&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.wx();this.gi("play");-1==this.Za&&this.gi("resume");this.Za=1;var b=g.Qa(this);b in Q0||(Q0[b]=this);WEa();XEa(this,a);return!0};
g.k.stop=function(a){S0(this);this.Za=0;a&&(this.progress=1);YEa(this,this.progress);this.gi("stop");this.tu()};
g.k.pause=function(){this.kc()&&(S0(this),this.Za=-1,this.gi("pause"))};
g.k.oa=function(){0==this.Za||this.stop(!1);this.gi("destroy");T0.le.oa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.mz=function(){this.gi("animate")};
g.k.gi=function(a){this.dispatchEvent(new ZEa(a,this))};
g.Ua(ZEa,g.zl);g.Ua(U0,T0);U0.prototype.u=g.Ka;U0.prototype.mz=function(){this.u();U0.le.mz.call(this)};
U0.prototype.tu=function(){this.u();U0.le.tu.call(this)};
U0.prototype.wx=function(){this.u();U0.le.wx.call(this)};
g.Ua(V0,U0);V0.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(W0,g.F);W0.prototype.Na=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.ap(a,b,c);this.i.push(a);return a};
W0.prototype.BB=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.jp(a,b,c);this.i.push(a);return a};
W0.prototype.dc=function(a){g.bp(a);g.kb(this.i,a)};
W0.prototype.oa=function(){g.bp(this.i);this.i.length=0;g.F.prototype.oa.call(this)};g.u($0,g.hM);g.k=$0.prototype;g.k.load=function(){g.hM.prototype.load.call(this);if(!a1(this)){var a=g.TG(this.player.getVideoData());a?(a=Z0(a,aFa(this)),b1(this,a,!1)):bFa(this)}};
g.k.unload=function(){b1(this,null);this.u&&(this.u.abort(),this.u=null);g.hM.prototype.unload.call(this)};
g.k.tf=function(a,b){return a1(this)?"loadCustomEndscreenRenderer"===a?(a=Z0(b,"new"),b1(this,a),!0):null:null};
g.k.getOptions=function(){return a1(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.tb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<jGa.length;f++){var h=Math.abs(b.width-jGa[f]);if(-1===e||d>=h)e=f,d=h}d=kGa[e];this.l&&g.dg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.sg(e.element,Math.round(h.width*a.width),f);g.lg(e.element,m,n);g.kn(e.element,lGa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.kn(e.element,kGa);g.K(e.element,d);(e=g.me(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.dg(e,"height",f+"px")}}}}};
g.k.Yd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())i1(this,this.endscreen.impressionUrls),(a=g.qu())&&this.endscreen.visualElement&&g.yu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");i1(this,c.impressionUrls);(b=g.qu())&&g.yu(b,c.visualElement,void 0);this.player.T().u&&this.player.La("endscreenelementshown",
a)}};
g.k.ag=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.jn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.jn(b,"ytp-ce-shown");this.player.T().u&&this.player.La("endscreenelementhidden",a)}};
g.k.yS=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.kn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var jGa=[346,426,470,506,570,640,853,1280,1920],kGa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),lGa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var mFa={oX:"current",S1:"new"};var oFa={CLOSE:"close",h2:"openUrl",cN:"subscribe"},pFa={iV:"click",CLOSE:"close",IY:"hidden",r3:"rollOut",s3:"rollOver",a4:"shown"};var fGa={EU:"anchored",FK:"branding",CHANNEL:"channel",mX:"cta",LY:"highlightText",JZ:"label",PLAYLIST:"playlist",O2:"popup",k4:"speech",cN:"subscribe",B4:"title",VIDEO:"video",G5:"website"},eGa={FK:"branding",WU:"card",CX:"drawer",KY:"highlight",k0:"marker",W2:"promotion",TEXT:"text",M5:"widget"};g.u(s1,g.F);g.k=s1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.oB(a,b,{id:c});a.namespace="annotations_module";d&&this.Ma.set(a,d);e&&this.Qa.set(a,e);this.context.G.Sd([a])};
g.k.Nu=function(){this.context.l.subscribe("resize",this.Qv,this)};
g.k.nz=function(a,b,c,d,e,f){if(this.Ya)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.He(this.element)};
g.k.Qv=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=l1(a);if(f){var h=yFa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Gp(f||"");m&&n&&(n.v||n.list)?e.context.G.Mj(n.v,b,n.list,!1):g.LI(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);I1(this.context.logger,c,l,d);xFa(f)||(c=g.qu(),d=b.itct,c&&d&&g.Hu(c,g.ku(d)))}};
g.k.oa=function(){this.Ma.clear();this.Qa.clear();g.F.prototype.oa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.u(x1,s1);g.k=x1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.tg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Qv=function(){var a=this.isAvailable();g.ug(this.element,a);g.L(this.context.G.getRootNode(),g.aS.IV_DRAWER_ENABLED,a);O0(this.G)};
g.k.destroy=function(){this.G.Kr(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.Ho(this.X);g.bp(this.ra);this.Fa&&this.Fa.dispose();this.C&&this.C.dispose();s1.prototype.destroy.call(this)};
g.k.BN=function(){if(this.u){I1(this.context.logger,C1(this).tracking.close);var a=g.qu();a&&this.J&&g.Hu(a,this.J);w1(this)}};
g.k.NN=function(){g.L(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.ZO=function(){var a=g.qu(),b=C1(this);b=b?b.Ee:this.Ee;a&&b&&g.Fu(a,[b])};
g.k.YO=function(){var a=g.qu(),b=C1(this);b=b?b.Ee:this.Ee;a&&b&&g.Gu(a,[b])};
g.k.bM=function(){var a=C1(this);I1(this.context.logger,a.tracking.ZJ);var b=g.qu();b&&a&&g.Fu(b,[a.Oi,a.Ee])};
g.k.bP=function(){var a=g.qu(),b=C1(this);a&&b&&g.Gu(a,[b.Oi])};
g.k.aM=function(a){var b=C1(this),c=g.qu();this.i?a?(a=this.context.logger,I1(a,b.tracking.dy),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Oi&&g.Hu(c,b.Oi)):(a=this.context.logger,I1(a,b.tracking.dy),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ee&&g.Hu(c,b.Ee)):(a=this.context.logger,I1(a,b.tracking.dy),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Ee&&g.Hu(c,this.Ee))};g.u(D1,s1);D1.prototype.Nu=function(){s1.prototype.Nu.call(this);MFa(this)};
D1.prototype.show=function(){s1.prototype.show.call(this);var a=g.qu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Fu(a,[g.ku(b.itct)])};
D1.prototype.hide=function(){s1.prototype.hide.call(this);var a=g.qu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Gu(a,[g.ku(b.itct)])};g.u(E1,D1);
E1.prototype.show=function(){if(!this.isActive){D1.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ba:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.ug(this.l,!1);var b=this.createElement({D:"div",Ba:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=tFa(this.annotation))&&t1(this,this.l,b,this.annotation.id,
a.session_data);QFa(this,a);this.J=!0}g.ug(this.element,!0);this.isActive=!0;this.l&&NFa(this,this.l)}};
E1.prototype.hide=function(){this.isActive&&(D1.prototype.hide.call(this),g.ug(this.element,!1),this.isActive=!1)};
E1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);D1.prototype.destroy.call(this)};g.u(F1,D1);g.k=F1.prototype;g.k.show=function(){this.isActive||(D1.prototype.show.call(this),this.W||(SFa(this),this.W=!0),g.ug(this.element,!0),g.Dm(function(){g.jn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,H1(this),TFa(this),UFa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.nz=function(a,b,c,d,e,f){return this.isCollapsed?!1:D1.prototype.nz.call(this,a,b,c,d,e,f)};
g.k.sO=function(a){this.L=!0;G1(this,500,a)};
g.k.rO=function(){this.L=!1;VFa(this)};
g.k.lO=function(a){a.stopPropagation();this.hide()};
g.k.mO=function(a){a.stopPropagation();H1(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();D1.prototype.destroy.call(this)};g.u(J1,g.hM);g.k=J1.prototype;g.k.tf=function(a,b){if(!iGa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.A_(b))&&K1(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(DFa(this.i,b),O0(this.player)),!0}return null};
g.k.getOptions=function(){return iGa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Jp=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.hF||a.L.get(b.videoId)||g.UG(b)||g.VG(b)?!0:!1};
g.k.xx=function(){if(this.B){var a=this.player.Xa().getVideoContentRect(!0);g.sg(this.B.element,a.width,a.height);g.lg(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Ck();a=this.i;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.k.cM=function(a){YFa(this,a.state);g.U(a.state,2)&&(this.Gh()&&this.pk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Kr(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Sp(h)&&h.responseXML?h.responseXML:null)&&(K1(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.hM.prototype.load.call(this);YFa(this,this.player.rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rp()&&(a=aGa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&bGa(e,f);f=f&&(f.Uv||f.Qs);if(!c.jl||f)c.ra?ZFa(this,c.ra,e):(this.u=function(){b.fb(e)},this.player.addEventListener("videodatachange",this.u));
g.YL(this.player,this.B.element,4);this.xx();(f=g.UG(c))&&gGa(this,f);(f=g.VG(c))&&f.featuredChannel&&hGa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.fb=function(a){var b=this.player.getVideoData();b.ra&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),ZFa(this,b.ra,a))};
g.k.unload=function(){this.player.Df("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,O0(this.player));this.W=!1;this.I&&(this.I.abort(),this.I=null);this.J={};this.l.hide();g.hM.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.YI=function(a){a===this.player.getVideoData().videoId&&(this.loaded?cGa(this):this.load())};
g.k.Gh=function(){return!!this.i&&this.i.isAvailable()};
g.k.pk=function(){this.Gh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Gh();this.i&&(a?c?v1(this.i,c,b):v1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):w1(this.i))};
g.k.Kr=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.oa=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.YI,this);g.jn(this.player.getRootNode(),g.aS.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.sp(a[b]);this.X.length=0;g.hM.prototype.oa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.nM.annotations_module=J1;g.nM.creatorendscreen=$0;})(_yt_player);
