(function(g){var window=this;'use strict';var P1=function(a){a.isActive()||a.start()},Q1=function(a){var b={languageCode:a.languageCode,
languageName:a.languageName,displayName:g.oF(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.i,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},R1=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},mGa=function(a,b){var c=new g.nF;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},nGa=function(){this.l=[];
this.i=[]},S1=function(a,b){return b?a.i.concat(a.l):a.i},T1=function(a,b){switch(b.kind){case "asr":oGa(b,a.l);
break;default:oGa(b,a.i)}},oGa=function(a,b){g.cb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},U1=function(){g.F.call(this);
this.l=new nGa;this.C=[]},V1=function(a,b,c){U1.call(this,a);
this.audioTrack=c;this.i=null;this.C=b.iF},W1=function(){this.segments=[]},pGa=function(a,b){var c=g.ub(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.rb(a.segments,c,0,b),g.rb(a.segments,c+1,0,b)))},X1=function(a,b,c,d,e,f){g.F.call(this);
this.policy=a;this.player=b;this.X=c;this.I=d;this.C=e;this.L=f;this.W=this.player.T();this.B=new W1;this.l=this.u=this.i=null;this.J=new g.J(this.BH,1E3,this);this.events=new g.$L(this);g.H(this,this.J);g.H(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.cE);this.cE();this.BH()},qGa=function(a,b){var c=g.xw(g.Ww(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.Et(c,d,3,100).then(function(e){a:{a.Ha();if(a.u){var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.wz(e);if(h){e=g.Ww(a.u,a.policy,{});f=a.u;g.Ew(f.l,e,h);f.requestId=e.get("req_id");qGa(a,a.u);break a}f||null==a.I||(h=a.u.i[0],a.C?a.I(e.response,1E3*(h.startTime+a.player.Kc())):a.I(e.responseText,1E3*(h.startTime+a.player.Kc())))}a.u=null;a.l=null}});
a.u=b;pGa(a.B,a.u.i[0].Ia)},Y1=function(a,b){U1.call(this,b.T());
this.i=a;this.G=b;this.u=null;this.B=!1;this.I=g.hE(this.G.T())&&!this.i.isManifestless},sGa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.iM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.xEa.get(e);null==n&&(n=rGa[e]||rGa[e.replace(/-/g,"_")],g.xEa.set(e,n));h=n||h}c.push(new g.nF({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},tGa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},uGa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.iM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},Z1=function(a,b,c,d,e){U1.call(this,e||null);
this.videoId=b;this.aH=d;this.B={};this.i=null;b=c||g.Gp(a).hl||"";b=b.split("_").join("-");this.u=g.Ip(a,{hl:b})},$1=function(a){if(!vGa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(wGa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},a2=function(a,b,c,d,e,f){var h={};
g.Sa(h,b);g.Sa(h,a.params);g.Sa(h,c);var l={};g.Sa(l,b.cd);a.params.cd&&g.Sa(l,a.params.cd);g.Sa(l,c.cd);h.cd=l;g.V.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.Hf?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ra=!1;this.l=a;this.Ca=this.va=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.Ma=.96*f;this.i=h;this.Fb=c;this.B=
this.ya("captions-text");this.qb=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Aa=d/360*16;this.type=0;this.Qa=this.Aa*xGa(l);a=new g.au(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.fM,this);a.subscribe("dragmove",this.eM,this);a.subscribe("dragend",this.dM,this);this.Ya=this.Va=0;b="";this.i.windowOpacity&&(a=$1(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,
display:!1===this.i.isVisible?"none":"","text-align":yGa[this.i.textAlign]};this.qb&&(a["border-radius"]=b?this.Qa/8+"px":"");if(this.u=2===this.l.params.Hf||3===this.l.params.Hf)b=this.element,c="vertical-rl",1===this.i.YC&&(c="vertical-lr"),g.we&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.dg(b,"-o-writing-mode",c),g.dg(b,"-webkit-writing-mode",c),g.dg(b,"writing-mode",c),g.dg(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3===this.l.params.Hf&&(g.dg(b,"text-orientation",""),g.dg(b,"transform",
"rotate(180deg)"));g.dg(this.element,a);switch(this.i.Xi){case 0:case 1:case 2:g.K(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},xGa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},zGa=function(a,b){var c={},d=b.background?b.background:a.i.cd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.cd.backgroundOpacity;d=$1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.qb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Qa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Aa*xGa(b)+"px";d=1;e=b.color||a.i.cd.color;if(b.color||null!=b.textOpacity)e=$1(e),d=null==b.textOpacity?a.i.cd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Wz&&(h=e=b.Wz);var l=a.Aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.eq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.cd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.lj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.JO&&(c.visibility="hidden");1===b.WG&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.AE||g.es,3===a.l.params.Hf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Hj||2===b.Hj||3===b.Hj||4===b.Hj||5===b.Hj)if(g.AE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Hj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},AGa=function(a){a.I=g.De("SPAN");
g.dg(a.I,{display:"block"});g.K(a.I,"caption-visual-line");a.B.appendChild(a.I)},BGa=function(a,b){var c=g.De("SPAN");
g.dg(c,{display:"inline-block","white-space":"pre-wrap"});g.dg(c,zGa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.dg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.dg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},CGa=function(a,b,c){a.ra=a.ra||!!c;
var d={};g.Sa(d,a.i.cd);g.Sa(d,c||b.i);g.Sa(d,a.Fb.cd);(c=!a.I)&&AGa(a);for(var e=a.va&&a.Ca&&g.Tb(d,a.Ca)?a.va:BGa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(AGa(a),e=BGa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ee(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.AE||!g.hg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.hg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.ye?g.dg(e,m,"1em"):g.dg(e,m,"0.5em")))}a.Ca=d;a.va=e;a.C.push(b)},b2=function(a,b,c,d,e,f,h){a2.call(this,a,b,c,d,e,f,h);
this.type=1},c2=function(a,b,c,d,e,f,h){a2.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.X=this.L=this.Da=0;this.Y=NaN;this.gb=0;this.ub=null;this.Fa=new g.J(this.GR,433,this);g.K(this.element,"ytp-caption-window-rollup");g.H(this,this.Fa);g.dg(this.element,"overflow","hidden")},DGa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.YC&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},EGa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.Xl,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Dm)?(e=g.De("SPAN"),g.Ne(e,"\u2013".repeat(d)),g.dg(e,zGa(a,a.i.cd)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.X=c.call(b,a.Y,a.gb,(a.u?d.offsetHeight:d.offsetWidth)+1)},FGa=function(a,b){EGa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.Da){var d=0<c&&0===a.Da;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.bn(a.Fa));g.dg(a.B,"transform",DGa(a,c));a.Da=c}EGa(a)},d2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.oB.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},e2=function(a,b,c,d,e){g.oB.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},GGa=function(a){var b="_"+f2++;
return new e2(0,0x8000000000000,0,b,a)},IGa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Zd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=HGa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new d2(a,b,e,c,l,d,m)}switch(m.Zd){case 9:case 10:m.Hj=1;break;case 11:m.Hj=2;break;case 12:m.Hj=3;break;case 13:m.Hj=4;break;case 14:m.Hj=5}return new d2(a,b,e,c,l.textContent||"",d,m)},HGa=function(a,b,c,d,e){var f=g.eq(),h=
f?g.De("DIV"):g.De("RUBY"),l=g.De("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.De("DIV"):g.De("RP");a.textContent=b;h.appendChild(a);b=f?g.De("DIV"):g.De("RT");b.textContent=c;h.appendChild(b);c=e.Zd;if(10===c||11===c||12===c||13===c||14===c)if(g.dg(b,"text-emphasis-style","filled circle"),g.dg(b,"text-emphasis-color","currentcolor"),g.dg(b,"webkit-text-emphasis","filled circle"),11===e.Zd||13===e.Zd)g.dg(b,"webkit-text-emphasis-position","under left"),g.dg(b,"text-emphasis-position","under left");c=!0;if(4===e.Zd||7===e.Zd||12===e.Zd||
14===e.Zd)g.dg(h,"ruby-position","over"),g.dg(h,"-webkit-ruby-position","before");else if(5===e.Zd||6===e.Zd||11===e.Zd||13===e.Zd)g.dg(h,"ruby-position","under"),g.dg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.De("DIV"):g.De("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.dg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.dg(f,"display","none"),f=f.nextElementSibling,g.dg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.dg(h.lastElementChild,"display","none"),d?(g.dg(h,"padding-top","0.6em"),g.dg(f,"top","0")):(g.dg(h,"padding-bottom","0.6em"),g.dg(f,"bottom","0")));return h},g2=function(){g.F.apply(this,arguments)},h2=function(a){g2.call(this);
this.C=a;this.B={};this.W={};this.X={};this.I="_"+f2++;this.L={};this.u=this.i=null;this.J=!0},i2=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},j2=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},k2=function(a,b){a=i2(a,b);
return void 0!==a?a:null},m2=function(a,b){a=a.getAttribute(b);
if(null!=a)return l2.test(a),a},JGa=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.X[d]:a.C);a=k2(b,"mh");null!=a&&(c.yr=a);a=k2(b,"ju");null!=a&&(c.textAlign=a);a=k2(b,"pd");null!=a&&(c.Hf=a);a=k2(b,"sd");null!=a&&(c.YC=a);a=m2(b,"wfc");null!=a&&(c.windowColor=a);b=i2(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},KGa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.W[d]);a=k2(b,"ap");null!=a&&(c.Xi=a);a=i2(b,"cc");null!=a&&(c.Dm=a);a=i2(b,"ah");null!=a&&(c.Nh=a);a=i2(b,"rc");null!=a&&(c.Xl=a);b=i2(b,"av");null!=b&&(c.Jj=b);return c},LGa=function(a,b,c,d){var e={};
g.Sa(e,KGa(a,b));g.Sa(e,JGa(a,b));d?g.Tb(e,a.C)?(d=a.I,e=a.C):d="_"+f2++:d=b.getAttribute("id")||"_"+f2++;a=i2(b,"t")+c;b=i2(b,"d")||0x8000000000000;if(2===e.Hf||3===e.Hf)c=e.Xl,e.Xl=e.Dm,e.Dm=c;return new e2(a,b,0,d,e)},n2=function(a){g2.call(this);
this.I=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},o2=function(a){a=g.Zd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},MGa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Xl=a);b=b.ccColCount;void 0!==b&&(f.Dm=b);if(2===f.Hf||3===f.Hf)b=f.Xl,f.Xl=f.Dm,f.Dm=b;return new e2(c,d,0,e,f)},q2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new p2(this);this.C=new p2(this);this.i=[];this.clear()},OGa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Ao:a,
ym:b,result:0};a=NGa[a];b=NGa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.ym===d;if(d)return{Ao:a,ym:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ao:a,ym:b,result:2};return{Ao:a,ym:b,result:3}},QGa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,PGa(a.B,b,c,d))},RGa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?QGa(a,d.HF,d.IF,b):1===d.type&&a.l&496&&PGa(a.C,d.HF,d.IF,b);a.i.length=0},r2=function(){this.type=0},s2=function(){this.state=this.ym=this.Ao=0},SGa=function(){this.timestamp=this.i=0},t2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new r2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new SGa}},u2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},XGa=function(a,b){switch(a){case 0:return TGa[(b&127)-32];
case 1:return UGa[b&15];case 2:return VGa[b&31];case 3:return WGa[b&31]}return 0},v2=function(a){return a.u[a.row][a.l]},w2=function(a,b,c){2<=b&&1<a.l&&(--a.l,v2(a).i=0);
var d=v2(a);d.timestamp=a.C.time+0;d.i=XGa(b,c);32>a.l&&a.l++},YGa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},x2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},y2=function(a){a.row=0<a.i?a.i:1;
a.l=1;x2(a,0,15)},z2=function(a){this.u=a;
this.C=0;this.style=new r2;this.I=new t2(this.u);this.J=new t2(this.u);this.text=new t2(this.u);this.l=this.I;this.B=this.J;this.i=this.l},A2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(u2(d,c),y2(a.l),y2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(u2(d,c),x2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},ZGa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},$Ga=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},p2=function(a){this.i=a;
this.C=0;this.u=new z2(this.i);this.I=new z2(this.i);this.l=new s2;this.B=this.u},PGa=function(a,b,c,d){a.l.update();
b=OGa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ao;c=b.ym;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&w2(a,0,b),c&96&&w2(a,0,c),0!==b&&0!==c&&3===a.style.type&&u2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.Ao=e,b.ym=c,b.state=2,b=e&8?a.I:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;YGa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));x2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:w2(b.i,0,32);break a;case 48:57===c?(d=b.i,v2(d).i=0,32>d.l&&d.l++):w2(b.i,1,c&15)}break;case 2:c&32&&w2(b.i,2,c&31);break;case 3:c&32&&w2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:ZGa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,v2(d).i=0);break;case 36:d=b.i;b=v2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:A2(b,2,d);break;case 38:A2(b,3,d);break;case 39:A2(b,4,d);break;case 40:w2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);y2(d);$Ga(b);break;case 43:$Ga(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:u2(a,d)}x2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;u2(a,d);YGa(a,b,b+1,a.i-1);x2(a,a.row,1)}break;case 46:x2(b.B,0,15);break;case 47:u2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,ZGa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},aHa=function(){},B2=function(a,b,c){this.J=a;
this.I=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.J);this.l=[]},C2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},D2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},E2=function(a,b){g2.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new q2;this.i.l=1<<this.track},F2=function(a){if("string"===typeof a)return!1;
a=new B2(a,8,0);return bHa(a)},bHa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==D2(a))return!1;
a.version=C2(a);if(1<a.version)return!1;C2(a);C2(a);C2(a);return!0},G2=function(){g2.call(this)},cHa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.lj=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new d2(b,c,d,e.id,p.nodeValue,f||0<n,g.Qb(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Sa(r,l);cHa(a,b,c,d,e,!0,p,r,m)}}},H2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},dHa=function(a,b,c,d){d=Object.assign({yr:0},d);
return new e2(a,b,c,"_"+f2++,d)},I2=function(a){g.F.call(this);
this.l=a;this.i=null},fHa=function(a){var b={};
if(a=R1(a))b.lang=a,eHa.test(a)&&(b.Hf=1);return b},L2=function(a){g.hM.call(this,a);
var b=this;this.G=a;this.i=this.G.T();this.videoData=this.G.getVideoData();this.qb=this.G.Xa();this.B={cd:{}};this.C={cd:{}};this.Y=[];this.W={};this.Fa={};this.X=!1;this.Ya=g.zna(this.videoData,this.G);this.ub=!!this.videoData.captionTracks.length;this.Fb=!!this.videoData.Fi;this.Va="3"===this.i.controlsType;this.u=this.J=this.L=this.Da=this.Wa=null;this.Ma=new I2(this.i);this.l=null;this.Ca=new g.$L(this);this.Qa=new g.V({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.$n("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Bn(d));this.storage=c;c=a.Bd();d=!(!c||!c.Vu());this.gb=!(!c||!c.Wu());this.I=this.Va&&d&&!this.Ya;this.va=!this.I&&this.Va&&this.gb&&this.Ya;g.H(this,this.Ma);this.I?this.Aa=this.ra=null:(this.ra=new g.Zm(this.qD,void 0,this),g.H(this,this.ra),this.Aa=new g.J(this.WS,2E3,this),g.H(this,this.Aa));g.H(this,this.Ca);this.i.ea("caption_window_container_killswitch")||g.YL(this.player,this.Qa.element,4);g.H(this,this.Qa);this.I||
this.Ca.N(a,"resize",this.sD);this.Ca.N(a,"onPlaybackAudioChange",this.QP);this.Ca.N(a,g.rB("captions"),function(e){b.Yd(e)});
this.Ca.N(a,g.sB("captions"),function(e){b.ag(e)});
J2(this,K2(this,"display-settings")||{})},gHa=function(a){if(1===a.i.Fa||1===a.videoData.bq||"alwayson"===g.IG(a.videoData,"yt:cc"))return!0;
if(2===a.i.Fa){var b;g.lE(a.i)?b=(0,g.lEa)():b=K2(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=a.player.getAudioTrack().captionsInitialState;var d=g.IG(a.videoData,"yt:cc");if(void 0===M2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.IG(a.videoData,"yt:cc")},N2=function(a,b){if(a.l&&(void 0===b||!b)||
!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.l||"FORCED_ON"===a.u},M2=function(a){var b=void 0,c=g.Xq(g.Vq.getInstance(),65);
g.lE(a.i)&&null!=c&&(b=!c);return b},P2=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
b||(b=a.Fb?!1:a.ub?!1:!0);b=S1(a.u.l,b);for(var c=[a.videoData.captionsLanguagePreference,a.i.captionsLanguagePreference,g.IG(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(R1(b[e])===c[d])return b[e];return a.J&&a.J.B?a.J.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||O2(a)}return null},O2=function(a){return a.J&&a.J.l},Q2=function(a){var b=O2(a);
return!!b&&a.l===b},hHa=function(a,b){var c=a.G.Bd().Qe().textTracks;
a=a.l.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},S2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.X=c,a.X&&(g.lE(a.i)?(0,g.e0)(!!b):R2(a,"module-enabled",!!b)));a.l=b;N2(a)&&(a.l=O2(a));a.load()},iHa=function(a,b){a.i.ea("caption_window_container_killswitch")?g.YL(a.player,b,4):a.Qa.element.appendChild(b)},jHa=function(a,b){var c=a.qb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.l?a.l.languageCode:null;!b.params.Hf&&d&&eHa.test(d)&&(b.params.Hf=1);d=a.qb.getPlayerSize();switch(null!=b.params.yr?b.params.yr:1<b.i.length?1:0){case 1:return new b2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);case 2:return new c2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);default:return new a2(b,a.B,a.C,c,d.width,d.height,a.i.experiments)}},J2=function(a,b,c){c=void 0===c?!1:c;
var d=T2.cd;a.B={};g.Sa(a.B,T2);a.B.cd={};g.Sa(a.B.cd,d);a.C={cd:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;l2.test(f);e.cd.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;l2.test(f);e.cd.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||T2.windowColor;l2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.cd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.cd.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.lj?3:d.bold?1:d.lj?2:0);f=f.cd;switch(e){case 1:f.bold=!0;delete f.lj;break;case 2:delete f.bold;f.lj=!0;break;case 3:f.bold=!0;f.lj=!0;break;default:delete f.bold,delete f.lj}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.cd.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=T2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.cd.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.cd.fontFamily=f;a.loaded&&a.sD();c&&R2(a,"display-settings",b)},lHa=function(a,b){b&&!a.L?(b=GGa({Hf:0,
lang:"en"}),a.L=[b,new d2(b.start,b.end-b.start,0,b.id,"Captions look like this")],a.player.Sd(a.L)):!b&&a.L&&(kHa(a,a.L),a.L=null)},kHa=function(a,b){a.player.Eg(b);
g.zb(b,function(c){g.kb(this.Y,c)},a);
P1(a.ra)},K2=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},R2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.vM.prototype.Ss=g.ca(23,function(){this.Z();for(var a=g.me(document,"track",void 0,this.i),b=0;b<a.length;b++)g.He(a[b])});
g.iR.prototype.Ss=g.ca(22,function(){this.i.Ss()});
g.vM.prototype.Wu=g.ca(21,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.iR.prototype.Wu=g.ca(20,function(){return this.i.Wu()});
g.vM.prototype.Vu=g.ca(19,function(){return!!this.i.textTracks});
g.iR.prototype.Vu=g.ca(18,function(){return this.i.Vu()});
g.vM.prototype.Js=g.ca(17,function(a){this.Z();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.iR.prototype.Js=g.ca(16,function(a){this.i.Js(a)});
g.rv.prototype.Ew=g.ca(1,function(a){return(a=this.bj(a))?a.l:0});
g.yy.prototype.Ew=g.ca(0,function(){return 0});
var eHa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,rGa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (World)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",
as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",
bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",
cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",
en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",
fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",
hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",
kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",
ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",
mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",
nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",
rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",
sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",
tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",
xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};g.u(U1,g.F);g.k=U1.prototype;g.k.Xw=function(){};
g.k.Yw=function(){};
g.k.gm=function(){};
g.k.Xq=function(){return""};
g.k.jJ=function(){return!1};
g.k.oa=function(){this.gm();g.F.prototype.oa.call(this)};
g.u(V1,U1);V1.prototype.Xw=function(a,b,c){var d=this;this.Ha();b=this.Xq(a,b);this.gm();this.i=g.Xp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
V1.prototype.Yw=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())T1(this.l,c.value);a()};
V1.prototype.Xq=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.eq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=R1(a));return g.Ip(c,d)};
V1.prototype.gm=function(){this.i&&this.i.abort()};
W1.prototype.contains=function(a){a=g.ub(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
W1.prototype.length=function(){return this.segments.length/2};
g.u(X1,g.F);g.k=X1.prototype;g.k.oa=function(){g.F.prototype.oa.call(this);this.l&&this.l.cancel()};
g.k.cE=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Kc();var b=this.i;this.i=g.ab(this.X.Tm(a).i);b!==this.i&&this.L&&this.L()};
g.k.reset=function(){this.B=new W1;this.l&&(this.l.cancel(),this.l=null)};
g.k.BH=function(){this.Ha();var a;if(a=null!=this.i)a=this.i,a=a.i.lm(a);!a||this.l||this.i&&30<this.i.startTime-this.player.getCurrentTime()||(a=this.i,a=a.i.ls(a),a.i[0].duration?(this.B.contains(a.i[0].Ia)||qGa(this,a),this.i=g.ab(a.i)):!g.P(this.W.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.Kc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.J.start()};
g.u(Y1,U1);g.k=Y1.prototype;g.k.Xw=function(a,b,c){var d=this;this.gm();b=tGa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?uGa(this,b,"386"):uGa(this,b));if(b){var e=1E3*(b.index.Ew(b.index.dj())-b.index.Xf(b.index.dj()));this.u=new X1(new g.xna,this.G,b,function(f,h){c(f,a,h,e)},this.I||g.qy(b.info),function(){d.u&&d.u.reset();
d.B=!0})}};
g.k.jJ=function(){var a=this.B;this.B=!1;return a};
g.k.Yw=function(a){var b=this.I?[new g.nF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.nF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?sGa(this,"386"):sGa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())T1(this.l,c.value);a()};
g.k.gm=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.Xq=function(){return""};
g.u(Z1,U1);Z1.prototype.Xw=function(a,b,c){var d=this;this.Ha();b=this.Xq(a,b);this.gm();this.i=g.Xp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
Z1.prototype.Yw=function(a){var b=this,c=this.u,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.aH&&(d.asrs=1);c=g.Ip(c,d);this.gm();this.i=g.Xp(c,{format:"RAW",onSuccess:function(e){b.i=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");T1(b.l,new g.nF({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.B[m.languageCode]=m.languageName,b.C.push(m)}a()},
withCredentials:!0})};
Z1.prototype.Xq=function(a,b){var c=this.u;b={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(b.tlang=R1(a));return c=g.Ip(c,b)};
Z1.prototype.gm=function(){this.i&&this.i.abort()};
var l2=/^#(?:[0-9a-f]{3}){1,2}$/i,wGa=/#(.)(.)(.)/,vGa=/^#(?:[0-9a-f]{3}){1,2}$/i;var yGa=["left","right","center","justify"];g.u(a2,g.V);g.k=a2.prototype;g.k.fM=function(a,b){var c=g.rg(this.element,this.element.parentElement);this.Va=a-c.x;this.Ya=b-c.y;g.K(this.element,"ytp-dragging")};
g.k.eM=function(a,b){var c=g.tg(this.element);a=a-this.Va-.02*this.playerWidth;var d=b-this.Ya-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Zd(e,0,2));var f=(d+c.height/2)/this.Ma*3;f=Math.floor(g.Zd(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Zd(a,0,1);c=(d+f/2*c.height)/this.Ma;c=100*g.Zd(c,0,1);this.l.params.Xi=b;this.l.params.Jj=c;this.l.params.Nh=a;this.i.Xi=b;this.i.Jj=c;this.i.Nh=a;this.FJ()};
g.k.dM=function(){g.jn(this.element,"ytp-dragging")};
g.k.FJ=function(){this.Nr(this.C)};
g.k.Vb=function(){return this.type};
g.k.Nr=function(a){var b=Math.min(this.BG(),this.maxWidth),c=this.AG(),d="";3===this.l.params.Hf&&(d="rotate(180deg)");g.dg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Kz(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Nh+2;d=this.i.Xi;switch(d){case 0:case 3:case 6:(b=this.i.cd.fontSizeIncrement)&&0<b&&2!==this.i.Hf&&3!==
this.i.Hf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Jj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.dg(this.element,
a)};
g.k.Kz=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ra||this.C.length>b)b=0,this.ra=!1,this.C=[],this.I=this.Ca=this.va=null,g.Fe(this.B);for(;b<a.length;b++)CGa(this,a[b])};
g.k.BG=function(){return 0};
g.k.AG=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.u(b2,a2);b2.prototype.Kz=function(a){var b=this.l.i;a2.prototype.Kz.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Sa(d,c.i);g.Sa(d,mHa);var e=c.i;var f=d}CGa(this,c,d)}};
var mHa={JO:!0};g.u(c2,a2);g.k=c2.prototype;g.k.FJ=function(){this.Fa.eh()};
g.k.GR=function(){g.jn(this.element,"ytp-rollup-mode");this.Nr(this.ub,!0)};
g.k.AG=function(){return this.u?this.X:this.L};
g.k.BG=function(){return this.u?this.L:this.X};
g.k.Nr=function(a,b){this.ub=a;if(this.l.params.Xl){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.gb=this.X;this.L=this.X=0;a2.prototype.Nr.call(this,a);FGa(this,b)}a2.prototype.Nr.call(this,a)};g.u(d2,g.oB);d2.prototype.toString=function(){return g.oB.prototype.toString.call(this)};g.u(e2,g.oB);e2.prototype.toString=function(){return g.oB.prototype.toString.call(this)};
var f2=0;g.u(g2,g.F);g2.prototype.l=function(){return[]};
g2.prototype.reset=function(){};g.u(h2,g2);h2.prototype.reset=function(){this.L={};this.u=this.i=null;this.J=!0};
h2.prototype.l=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.B,h={},l=a.getAttribute("p");l&&g.Sa(h,this.B[l]);l=j2(a,"b");null!=l&&(h.bold=
l);l=j2(a,"i");null!=l&&(h.lj=l);l=j2(a,"u");null!=l&&(h.underline=l);l=k2(a,"et");null!=l&&(h.charEdgeStyle=l);l=k2(a,"of");null!=l&&(h.offset=l);l=m2(a,"bc");null!=l&&(h.background=l);l=m2(a,"ec");null!=l&&(h.Wz=l);l=m2(a,"fc");null!=l&&(h.color=l);l=k2(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=i2(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=i2(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=i2(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=k2(a,"rb");null!=l&&10!==l&&0!==l&&(h.Zd=10<l?l-
1:l);a=k2(a,"hg");null!=a&&(h.WG=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.X[c]=JGa(this,a);break;case "wp":c=a.getAttribute("id"),this.W[c]=KGa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=LGa(this,a,b,!1);(a=this.L[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.L[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.I;h=!!j2(a,"a");l=(i2(a,
"t")||0)+l;var m=i2(a,"d")||5E3;h||(!this.J&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.B[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var w=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===w.nodeType&&(y=w);if(y&&"s"===y.tagName){if((w=(w=y.getAttribute("p"))?this.B[w]:null)&&w.Zd&&(1===w.Zd?(w=r.slice(t,t+4),4===w.length&&(x=IGa(l,m,
f,h,n,w,this.B),t+=3)):x=IGa(l,m,f,h,n,[y],this.B)),!x){var E=y;x=l;y=m;w=f;var D=h,G=n,I=E.textContent?E.textContent:"",T=E.getAttribute("p");T=T?this.B[T]:null;E=i2(E,"t")||0;x=new d2(x+E,y-E,G,w,I,D,T)}}else x=new d2(l,m,n,f,w.textContent||"",h,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.I&&(this.i=LGa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var nHa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(n2,g2);n2.prototype.reset=function(){this.u.clear()};
n2.prototype.l=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.lj=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.Wz=o2(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=o2(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=o2(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Zd=10<h?h-1:h,f.Hj=nHa.get(f.Zd));e.hgHorizGroup&&(f.WG=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.C.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.yr=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Hf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.YC=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=o2(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.B.get(h)),void 0!==e.ahHorPos&&
(f.Nh=e.ahHorPos),void 0!==e.apPoint&&(f.Xi=e.apPoint),void 0!==e.avVerPos&&(f.Jj=e.avVerPos),void 0!==e.ccCols&&(f.Dm=e.ccCols),void 0!==e.rcRows&&(f.Xl=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=MGa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+f2++,h=MGa(this,l,d,e,f),a.push(h),this.u.set(f,h));0===e&&(e=5E3);h=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],w=t.utf8;if(w){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.yr?h.params.yr:1<h.i.length?1:0)&&m&&"\n"===w)continue;if(t=y&&1===y.Zd)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var E=p[t+1].pPenId;(E=this.i.get(E))&&E.Zd&&2===E.Zd?(E=p[t+2].pPenId,E=this.i.get(E),!E||!E.Zd||3>E.Zd?t=!1:(E=p[t+3].pPenId,t=(E=this.i.get(E))&&
E.Zd&&2===E.Zd?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;E=p[l+2].utf8;var D=this.i.get(p[l+2].pPenId);w=HGa(w,x,E,t,D);m=new d2(d,e,n,f,w,m,y);l+=3}else m=new d2(d+x,e-x,n,h.id,w,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};q2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
q2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var NGa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];r2.prototype.set=function(a){this.type=a};
r2.prototype.get=function(){return this.type};
s2.prototype.clear=function(){this.state=0};
s2.prototype.update=function(){this.state=2===this.state?1:0};
s2.prototype.isValid=function(){return 0!==this.state};
s2.prototype.matches=function(a,b){return this.isValid()&&a===this.Ao&&b===this.ym};
SGa.prototype.reset=function(){this.timestamp=this.i=0};
t2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
t2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
t2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var TGa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],UGa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],VGa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],WGa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];z2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.I;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
p2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.I.reset(a,1)};aHa.prototype.B=function(){};g.u(B2,aHa);B2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+f2++;c=c/1E3-this.I;d=d/1E3-this.I;a=new e2(c,d-c,5,f,{textAlign:0,Xi:0,Nh:2.5*b,Jj:5.33*a});e=new d2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.u(E2,g2);E2.prototype.l=function(a){a=new B2(a,a.byteLength,this.u);if(bHa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=D2(a)*(1E3/45):1===a.version&&(a.u=4294967296*D2(a)+D2(a)),a.C=C2(a);0<a.C;a.C--){var b=C2(a),c=C2(a),d=C2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,HF:c,IF:d,order:b.i.length}))}RGa(this.i,a);return a.l}return[]};
E2.prototype.reset=function(){this.i.clear()};g.u(G2,g2);
G2.prototype.l=function(a,b){var c=[];a=a.split(oHa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!pHa.test(e)){var h=U2.exec(e);if(h&&4<=h.length){var l=H2(h[1]),m=H2(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null,r="",t=null,w="";h.textAlign=2;n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Jj=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.Nh=Number.parseInt(t,10);2===x.length&&(w=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||(h.Jj=100,r||(r="end"));if(!t)switch(h.textAlign){case 0:h.Nh=0;break;case 1:h.Nh=100;break;default:h.Nh=50}p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}h.Xi=0>p||8<p?7:p;e=e.substring(U2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=dHa(l,m,5,w),m=new d2(l,m,5,f.id,h,!1,g.Qb(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(qHa),1===r.length?(h=5,w=dHa(l,m,h,w)):(p=h=6,w=Object.assign({Dm:32},w),w=new e2(l,m,p,"_"+f2++,w)),c.push(w),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.A_("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,cHa(this,p,m-(p-l),h,w,0<t,y,e,c)):p=H2(n)+f}U2.lastIndex=0}}return c};
var pHa=/^NOTE/,oHa=/(?:\r\n|\r|\n){2,}/,U2=/^((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})[\t ]+--\x3e[\t ]+((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})(?:[\t ]*)(.*)(?:\r\n|\r|\n)/gm,qHa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.lR.Qw(G2,{l:"wvppt"});g.u(I2,g.F);I2.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
I2.prototype.reset=function(){this.i&&this.i.reset()};
I2.prototype.oa=function(){g.F.prototype.oa.call(this);this.clear()};var T2={windowColor:"#080808",windowOpacity:0,textAlign:2,Xi:7,Nh:50,Jj:100,cd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(L2,g.hM);g.k=L2.prototype;g.k.oa=function(){if(this.I||this.va){var a=this.G.Bd();a&&!a.Ha()&&a.Ss()}else lHa(this,!1);g.hM.prototype.oa.call(this)};
g.k.Jp=function(){if(this.Va)return this.I||this.va;var a=this.player.getAudioTrack().captionsInitialState;return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?N2(this):M2(this)||N2(this)?!0:gHa(this)};
g.k.load=function(){var a=this;g.hM.prototype.load.call(this);var b=!g.P(this.i.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();if(this.u)this.l&&(this.Ma.clear(),this.I?hHa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Xw(this.l,"json3",function(d,e,f,h){if(d){a.u.jJ()&&(a.Y=[],a.G.Df("captions"),P1(a.ra),a.Ma.reset());var l=a.Ma;f=f||0;h=h||0;if(l.l.ea("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Mv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),F2(d)||(d=g.Ve(new Uint8Array(d))))}}else"string"===typeof d||F2(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Mv(m,0,1835295092))&&m.size?g.Ve(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!F2(n))throw Error("Invalid binary caption track data");l.i||(l.i=new E2(r,e));var t=l.i.l(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.i||(l.i=new G2),p=l.i.l(e,r),.01>Math.random()&&g.nt(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.i||(l.i=new n2(fHa(e)));n=l.i.l(p,f);break b}catch(G){g.mt(G);n=[];break b}r=g.A_(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.i||(l.i=new h2(fHa(e),l.l));n=l.i.l(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var E=Error("Invalid caption track data");E.params=p;throw E;}t=n}var D=t}catch(G){g.mt(G),l.clear(),D=[]}else D=[];a.player.Sd(D);!a.X||a.va||Q2(a)||g.VD(a.i)||g.MD(a.i)||(g.cn(a.Aa),D=GGa({Xi:0,Nh:5,Jj:5,Xl:2,textAlign:0,Hf:0,lang:"en"}),a.Da=[D],l=["Click "," for settings"],a.Wa||(t=new g.YJ(g.nK()),g.H(a,t),a.Wa=t.element),t=D.end-D.start,(e=g.oF(a.l))&&
a.Da.push(new d2(D.start,t,0,D.id,e)),a.Da.push(new d2(D.start,t,0,D.id,l[0]),new d2(D.start,t,0,D.id,a.Wa,!0),new d2(D.start,t,0,D.id,l[1],!0)),a.player.Sd(a.Da),g.bn(a.Aa));!a.X||a.va||Q2(a)||(g.lE(a.i)?(0,g.e0)(!0):R2(a,"module-enabled",!0),a.J&&(a.J.C=a.l),a.player.Sp());a.X=!1}}),!b||this.I||this.va||Q2(this)||this.player.La("captionschanged",Q1(this.l))),b||(this.l&&!Q2(this)?this.player.La("captionschanged",Q1(this.l)):this.player.La("onCaptionsTrackListChanged"));
else{var c;this.Ya?c=new Y1(this.videoData.i,this.player):this.ub?c=new V1(this.i,this.videoData,this.player.getAudioTrack()):c=new Z1(this.videoData.Fi,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.i.captionsLanguagePreference||g.IG(this.videoData,"yt:cc_default_lang")||this.i.zd,this.videoData.zz,this.i);this.u=c;g.H(this,this.u);c.Yw(function(){var d=a.player.getAudioTrack().captionsInitialState,e;"CAPTIONS_INITIAL_STATE_UNKNOWN"===d?M2(a)||a.X||gHa(a)?e=P2(a,a.X):N2(a)&&
(e=O2(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===d?e=P2(a,a.X):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===d&&N2(a)&&(e=O2(a));if(a.I||a.va){var f=S1(a.u.l,!0);d=[];for(var h=0;h<f.length;h++){var l=f[h],m=g.De("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.oF(l));m.setAttribute("srclang",R1(l));m.setAttribute("id",l.toString());a.va||m.setAttribute("src",a.u.Xq(l,"vtt"));l===e&&m.setAttribute("default","1");d.push(m)}e=a.G.Bd();e.Js(d);e=e.Qe();a.gb&&a.Ca.N(e.textTracks,"change",
a.kS)}else!a.l&&e&&S2(a,e),a.player.La("onCaptionsTrackListChanged"),a.player.La("onApiChange")})}};
g.k.unload=function(){this.I&&this.l?hHa(this,!1):(this.Aa&&g.cn(this.Aa),this.player.Df("captions"),this.Y=[],this.u&&this.u.gm(),this.Ma.clear(),this.L&&this.player.Sd(this.L),this.sD());g.hM.prototype.unload.call(this);this.player.Sp();this.player.La("captionschanged",{})};
g.k.create=function(){this.Jp()&&this.load()};
g.k.kS=function(){for(var a=this.G.Bd().Qe().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=S1(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.l:null)!==b&&S2(this,b,!0)};
g.k.KT=function(){!this.l&&this.I||this.unload()};
g.k.Yd=function(a){this.Y.push(a);P1(this.ra)};
g.k.ag=function(a){g.kb(this.Y,a);this.u instanceof Y1&&this.u.I&&this.player.Eg([a]);P1(this.ra)};
g.k.QS=function(a){if(a instanceof e2){var b=this.W[a.id];b&&b.l!==a&&(b.dispose(),delete this.W[a.id],b=null);b||(b=jHa(this,a))&&(this.W[a.id]=b)}else b=a.windowId,this.Fa[b]||(this.Fa[b]=[]),this.Fa[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Qa.element.id};
g.k.WS=function(){kHa(this,this.Da);this.Da=null};
g.k.qD=function(){var a=this;this.ra.stop();g.Rb(this.Fa);this.Y.sort(g.qB);var b=this.Y;if(this.L){var c=g.Ie(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.zb(b,this.QS,this);g.Bb(this.W,function(d,e){a.Fa[e]?(d.element.parentNode||(d instanceof c2||d instanceof b2||g.Gb(a.W,function(f,h){h!==e&&f.l.params.Xi===d.l.params.Xi&&f.l.params.Nh===d.l.params.Nh&&f.l.params.Jj===d.l.params.Jj&&(f.dispose(),delete a.W[h]);return h===e},a),iHa(a,d.element)),d.Nr(a.Fa[e])):(d.dispose(),delete a.W[e])},this)};
g.k.aT=function(){J2(this,{},!0);g.P(this.i.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.La("captionssettingschanged")};
g.k.hO=function(){var a=T2.cd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.lj?3:a.bold?1:a.lj?2:0,textOpacity:a.textOpacity,windowColor:T2.windowColor,windowOpacity:T2.windowOpacity};var b=K2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.sK=function(a,b){var c={};g.Sa(c,K2(this,"display-settings"));g.Sa(c,a);J2(this,c,b);this.player.La("captionssettingschanged")};
g.k.sD=function(){!this.I&&this.loaded&&(g.Bb(this.W,function(a,b){a.dispose();delete this.W[b]},this),this.qD())};
g.k.tf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Zd(b,-2,4);this.sK({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&S2(this,this.l,!0);break;case "stickyLoading":void 0!==b&&this.i.u&&(g.lE(this.i)?(0,g.e0)(!!b):R2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.I)break;if(!g.Oa(b))break;if(g.Qb(b)){S2(this,null,!0);break}a=S1(this.u.l,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?mGa(e,b.translationLanguage):e)}!c||c===this.l&&this.loaded||(b=(0,g.Qma)(),a=R1(c),b.length&&a===b[b.length-1]||(b.push(a),(0,g.mEa)(b)),S2(this,c,!0))}else return this.loaded&&this.l&&!Q2(this)?Q1(this.l):{};return"";case "tracklist":return this.u?g.Oc(S1(this.u.l,!(!b||!b.includeAsr)),function(f){return Q1(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.I||void 0===b||lHa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.i.u&&a.push("stickyLoading");return a};
g.k.UA=function(){var a=this.l;return a?{cc:a.vssId}:{}};
g.k.zT=function(){this.loaded&&this.l&&!Q2(this)?(g.lE(this.i)?(0,g.e0)(!1):R2(this,"module-enabled",!1),this.unload(),N2(this,!0)&&S2(this,O2(this),!1)):S2(this,Q2(this)||!this.l?P2(this,!0):this.l,!0)};
g.k.QP=function(){var a=Q2(this);N2(this,a)?S2(this,this.player.getAudioTrack().l,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Jp()&&(a?S2(this,P2(this),!1):this.load()))};
g.lR.Qw(L2,{qD:"smucd"});g.nM.captions=L2;})(_yt_player);
