(function(g){var window=this;'use strict';var yHa=function(a,b){a.La("onAutonavCoundownStarted",b)},h3=function(a,b,c){var d=b.bb();
g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.cf(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.WF&&(b.lengthText?(f=b.lengthText||null,h=b.Ww||null):b.lengthSeconds&&(f=g.HK(b.lengthSeconds),h=g.HK(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.bM(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.WF?b.isLivePlayback:null,n=b instanceof g.WF?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.Ks||g.CI("Watch $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.Vm(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.Ns};b instanceof g.cM&&(d.playlist_length=b.length);a.update(d)},i3=function(a){var b=a.T(),c=b.l;
g.V.call(this,{D:"a",K:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",Ba:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ba:["ytp-autonav-timestamp"],ma:"{{duration}}"},{D:"div",Ba:["ytp-autonav-live-stamp"],ma:"Live"},{D:"div",
Ba:["ytp-autonav-upcoming-stamp"],ma:"Upcoming"},{D:"div",K:"ytp-autonav-list-overlay",S:[{D:"div",K:"ytp-autonav-mix-text",ma:"Mix"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",Ba:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ma:"{{title}}"},{D:"div",Ba:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ma:"{{author}}"},{D:"div",Ba:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ma:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.i=c;this.Na("click",this.onClick);this.Na("keypress",this.l)},k3=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;b=a.T();var d=b.l;this.G=a;this.suggestion=null;this.i=new g.V({D:"div",K:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",ma:"{{autoplayAlternativeHeader}}"},
{D:"a",K:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:d?b.C:""},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ba:["ytp-autonav-timestamp"],ma:"{{duration}}"},{D:"div",Ba:["ytp-autonav-live-stamp"],ma:"Live"},{D:"div",Ba:["ytp-autonav-upcoming-stamp"],ma:"Upcoming"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",S:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",
ma:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",ma:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",ma:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",ma:"{{author_and_views}}"}]}]}]});g.H(this,this.i);this.i.xa(this.element);d||this.N(this.i.ya("ytp-autonav-endscreen-link-container"),"click",this.uE);this.G.Xb(this.element,this,115127);this.G.Xb(this.i.ya("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({D:"div",K:"ytp-autonav-overlay"});
g.H(this,this.overlay);this.overlay.xa(this.element);this.u=new g.V({D:"div",K:"ytp-autonav-endscreen-button-container"});g.H(this,this.u);this.u.xa(this.element);this.cancelButton=new g.V({D:"button",Ba:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Cancel autoplay"},ma:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.xa(this.u.element);this.cancelButton.Na("click",this.nM,this);this.G.Xb(this.cancelButton.element,this,115129);this.playButton=
new g.V({D:"a",Ba:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Play next video"},ma:"Play Now"});g.H(this,this.playButton);this.playButton.xa(this.u.element);this.playButton.Na("click",this.uE,this);this.G.Xb(this.playButton.element,this,115130);this.B=new g.J(function(){j3(c)},500);
g.H(this,this.B);this.tE();this.N(a,"autonavvisibility",this.tE)},j3=function(a){var b=l3(a),c=Math.min(a.l?Date.now()-a.l:0,b);
m3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Mh()?a.select(!0):a.Mh()&&a.B.start()},l3=function(a){var b=a.G.Qo();
return 0<=b?b:g.Q(a.G.T().experiments,"autoplay_time")||1E4},m3=function(a,b){b=void 0===b?-1:b;
a=a.i.ya("ytp-autonav-endscreen-upnext-header");g.Fe(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(/\$SECONDS/gi)[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Ee("Up next in $SECONDS".slice(0,d)));var e=g.De("span");g.fn(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ne(e,b);a.appendChild(e);a.appendChild(g.Ee("Up next in $SECONDS".slice(d+c.length)));return}}g.Ne(a,"Up next")},n3=function(a,b){g.V.call(this,{D:"div",
Ba:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},p3=function(a){g.V.call(this,{D:"div",
Ba:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",S:[{D:"span",K:"ytp-upnext-header",ma:"Up Next"},{D:"span",K:"ytp-upnext-title",ma:"{{title}}"},{D:"span",K:"ytp-upnext-author",ma:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{D:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
S:[{D:"circle",K:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",S:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",
ma:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.C=this.ya("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.J(this.Xv,5E3,this);this.l=0;var b=this.ya("ytp-upnext-cancel");this.cancelButton=new g.V({D:"button",Ba:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},ma:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Na("click",this.oM,this);this.cancelButton.xa(b);this.cancelButton&&this.api.Xb(this.cancelButton.element,
this,115129);g.H(this,this.B);this.api.Xb(this.element,this,18788);b=this.ya("ytp-upnext-autoplay-icon");this.N(b,"click",this.pM);this.api.Xb(b,this,115130);this.vE();this.N(a,"autonavvisibility",this.vE);this.N(a,"mdxnowautoplaying",this.LQ);this.N(a,"mdxautoplaycanceled",this.MQ);this.N(a,"mdxautoplayupnext",this.rK);o3(this)&&(a=(a=g.UL(this.api.kb()))?a.gO():null)&&this.rK(a);g.L(this.element,"ytp-upnext-mobile",this.api.T().i)},o3=function(a){return 3===a.api.getPresentingPlayerType()},zHa=
function(a,b){return b?b:0<=a.api.Qo()?a.api.Qo():g.Q(a.api.T().experiments,"autoplay_time")||1E4},q3=function(a,b){b=zHa(a,b);
var c=Math,d=c.min;var e=(0,g.N)()-a.l;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.C.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Mh()&&!o3(a)?a.select(!0):a.Mh()&&a.i.start()},r3=function(a){n3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.V({D:"div",K:"ytp-suggestion-panel",S:[{D:"div",Ba:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ma:"More videos"}]});this.J=new g.V({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.I=!1;this.l=new k3(this.player);g.H(this,this.l);this.l.xa(this.element);a.getVideoData().Jc?this.i=this.l:(this.i=new p3(a),g.YL(this.player,this.i.element,4),g.H(this,this.i));this.overlay=
new g.V({D:"div",K:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.xa(this.element);this.B=new g.$L(this);g.H(this,this.B);g.H(this,this.table);this.table.xa(this.element);this.table.show();g.H(this,this.J);this.J.xa(this.table.element);this.hide()},AHa=function(a,b){return g.Oc(b.suggestions,function(c){c=g.wO(a.player.T(),c);
g.H(a,c);return c})},s3=function(a){var b=a.Vd();
b!==a.C&&(a.C=b,a.player.V("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},t3=function(a){n3.call(this,a,"subscribecard-endscreen");
this.i=new g.V({D:"div",K:"ytp-subscribe-card",S:[{D:"img",K:"ytp-author-image",U:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",S:[{D:"div",K:"ytp-author-name",ma:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.H(this,this.i);this.i.xa(this.element);var b=a.getVideoData();this.subscribeButton=new g.iN("Subscribe",null,"Unsubscribe",null,!0,!1,b.Vh,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.xa(this.i.ya("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.Ja);this.Ja();this.hide()},u3=function(a){var b=a.T(),c=g.Vy||g.gg?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Ba:e,U:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{D:"div",K:"ytp-videowall-still-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",S:[{D:"span",K:"ytp-videowall-still-info-bg",S:[{D:"span",K:"ytp-videowall-still-info-content",U:c,S:[{D:"span",K:"ytp-videowall-still-info-title",ma:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",
ma:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",ma:"Live"},{D:"span",K:"ytp-videowall-still-info-duration",ma:"{{duration}}"}]}]}]},{D:"span",Ba:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",K:"ytp-videowall-still-listlabel-length",S:[" (",{D:"span",ma:"{{playlist_length}}"},")"]}]},{D:"span",Ba:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:[{D:"span",
K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",K:"ytp-videowall-still-listlabel-length",ma:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.$L(this);g.H(this,this.i);this.Na("click",this.onClick);this.Na("keypress",this.u);this.i.N(a,"videodatachange",this.fb);a.Ih(this.element,this);this.fb()},v3=function(a){n3.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.J=!1;this.L=null;this.l=new g.$L(this);g.H(this,this.l);this.I=new g.J(function(){g.K(b.element,"ytp-show-tiles")},0);
g.H(this,this.I);var c=new g.V({D:"button",Ba:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},S:[g.fK()]});g.H(this,c);c.xa(this.element);c.Na("click",this.tM,this);this.table=new g.YJ({D:"div",K:"ytp-endscreen-content"});g.H(this,this.table);this.table.xa(this.element);c=new g.V({D:"button",Ba:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Next"},S:[g.gK()]});g.H(this,c);c.xa(this.element);c.Na("click",this.sM,this);a.getVideoData().Jc?this.i=new k3(a,!0):this.i=new p3(a);
g.H(this,this.i);g.YL(this.player,this.i.element,4);this.hide()},w3=function(a){return g.ZL(a.player)&&a.Ms()&&!a.B},BHa=function(a,b){return g.Oc(b.suggestions,function(c){c=g.wO(a.G.T(),c);
g.H(a,c);return c})},x3=function(a){var b=a.Vd();
b!==a.J&&(a.J=b,a.player.V("autonavvisibility"))},y3=function(a){g.hM.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.$L(this);g.H(this,this.listeners);this.env=a.T();CHa(a)?(this.u=!0,DHa(this),this.i?this.endScreen=new r3(a):this.endScreen=new v3(this.player)):this.env.Vc?this.endScreen=new t3(this.player):this.endScreen=new n3(this.player);g.H(this,this.endScreen);g.YL(this.player,this.endScreen.element,4);EHa(this);this.listeners.N(a,"videodatachange",this.fb,this);this.listeners.N(a,g.rB("endscreen"),function(c){b.Yd(c)});
this.listeners.N(a,g.sB("endscreen"),function(c){b.ag(c)})},DHa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Sf&&a.l===b.Jc)return!1;a.i=b.Sf;a.l=b.Jc;return!0},CHa=function(a){a=a.T();
return a.Fb&&!a.Vc},EHa=function(a){a.player.Df("endscreen");
var b=a.player.getVideoData();b=new g.oB(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.oB(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Sd([b,c])};
g.RL.prototype.Qo=g.ca(4,function(){return this.app.Qo()});
g.dW.prototype.Qo=g.ca(3,function(){return this.getVideoData().cF});
g.u(i3,g.V);i3.prototype.select=function(){(this.G.Mj(this.suggestion.bb().videoId,this.suggestion.ge,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.sA||void 0)||this.G.ea("web_player_endscreen_double_log_fix_killswitch"))&&this.G.Kb(this.element)};
i3.prototype.onClick=function(a){g.AM(a,this.G,this.i,this.suggestion.ge||void 0)&&this.select()};
i3.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.hp(a)||(this.select(),g.gp(a))}};
i3.prototype.Fe=function(a){g.L(this.element,"ytp-suggestion-card-with-margin",a)};g.u(k3,g.V);g.k=k3.prototype;g.k.Cs=function(a){this.suggestion!==a&&(this.suggestion=a,h3(this.i,a),this.playButton.Oa("url",this.suggestion.Vm()),this.Fe())};
g.k.Fe=function(){var a=this.G.Ck(!0,this.G.isFullscreen());g.L(this.element,"ytp-autonav-endscreen-small-mode",this.yf(a));g.L(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.Xx);g.L(this.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.G.Vd());g.L(this.G.getRootNode(),"countdown-running",this.Mh());g.L(this.element,"ytp-player-content",this.G.Vd());g.dg(this.overlay.element,{width:a.width+"px"});if(!this.Mh()){this.G.Vd()?m3(this,Math.round(l3(this)/
1E3)):m3(this);a=!!this.suggestion&&!!this.suggestion.Ns;var b=this.G.Vd()||!a;g.L(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.L(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.aK(this.u,this.G.Vd())}};
g.k.Mh=function(){return 0<this.l};
g.k.Pr=function(){this.Mh()||(this.l=Date.now(),j3(this),yHa(this.G,l3(this)),g.L(this.G.getRootNode(),"countdown-running",this.Mh()))};
g.k.Ap=function(){this.cm();j3(this)};
g.k.cm=function(){this.Mh()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.cm()};
g.k.uE=function(a){g.AM(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.Kb(this.playButton.element):a.currentTarget===this.i.ya("ytp-autonav-endscreen-link-container")&&(a=this.i.ya("ytp-autonav-endscreen-link-container"),this.G.eb(a,!0),this.G.Kb(a)),this.select())};
g.k.nM=function(){this.G.Kb(this.cancelButton.element);g.TL(this.G,!0)};
g.k.tE=function(){var a=this.G.Vd();this.C&&this.vb!==a&&g.aK(this,a);this.Fe();this.G.eb(this.element,a);this.G.eb(this.cancelButton.element,a);this.G.eb(this.i.ya("ytp-autonav-endscreen-link-container"),a);this.G.eb(this.playButton.element,a)};
g.k.yf=function(a){return 400>a.width||459>a.height};g.u(n3,g.V);g.k=n3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Ms=function(){return!1};
g.k.Vd=function(){return!1};
g.k.pH=function(){return!1};g.u(p3,g.V);g.k=p3.prototype;g.k.Xv=function(){this.notification&&(this.B.stop(),this.dc(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.Cs=function(a){this.suggestion=a;h3(this,a,"hqdefault.jpg")};
g.k.vE=function(){g.aK(this,this.api.Vd());this.api.eb(this.element,this.api.Vd());this.api.eb(this.ya("ytp-upnext-autoplay-icon"),this.api.Vd());this.cancelButton&&this.api.eb(this.cancelButton.element,this.api.Vd())};
g.k.YQ=function(){window.focus();this.Xv()};
g.k.Pr=function(a){var b=this;this.Mh()||(g.Io("a11y-announce","Up Next "+this.suggestion.title),this.l=(0,g.N)(),this.i=new g.J(function(){q3(b,a)},25),q3(this,a),yHa(this.api,zHa(this,a)));
g.jn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Mh=function(){return!!this.i};
g.k.Ap=function(){this.cm();this.l=(0,g.N)();q3(this);g.K(this.element,"ytp-upnext-autoplay-paused")};
g.k.cm=function(){this.Mh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.P(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.bb(),this.Xv(),this.notification=new Notification("Up Next",{body:b.title,icon:b.cf()}),this.u=this.N(this.notification,"click",this.YQ),this.B.start())}this.cm();this.api.nextVideo(!1,a)};
g.k.pM=function(a){!g.Ke(this.cancelButton.element,g.cp(a))&&g.AM(a,this.api)&&(this.api.Vd()&&this.api.Kb(this.ya("ytp-upnext-autoplay-icon")),this.select())};
g.k.oM=function(){this.api.Vd()&&this.cancelButton&&this.api.Kb(this.cancelButton.element);g.TL(this.api,!0)};
g.k.LQ=function(a){o3(this);this.show();this.Pr(a)};
g.k.rK=function(a){o3(this);this.suggestion&&this.suggestion.bb().videoId===a.bb().videoId||this.Cs(a)};
g.k.MQ=function(){o3(this);this.cm();this.hide()};
g.k.oa=function(){this.cm();this.Xv();g.V.prototype.oa.call(this)};g.u(r3,n3);g.k=r3.prototype;g.k.create=function(){n3.prototype.create.call(this);this.B.N(this.player,"appresize",this.Fe);this.B.N(this.player,"onVideoAreaChange",this.Fe);this.B.N(this.player,"videodatachange",this.fb);this.B.N(this.player,"autonavchange",this.wE);this.B.N(this.player,"autonavcancel",this.qM);this.fb()};
g.k.show=function(){n3.prototype.show.call(this);(this.I||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.TL(this.player,!1);g.ZL(this.player)&&this.Ms()&&!this.u?(s3(this),2===this.videoData.autonavState?this.player.T().ea("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Pr():3===this.videoData.autonavState&&this.i.Ap()):(g.TL(this.player,!0),s3(this));this.Fe()};
g.k.hide=function(){n3.prototype.hide.call(this);this.i.Ap();s3(this)};
g.k.Fe=function(){var a=this.player.Ck(!0,this.player.isFullscreen());s3(this);this.l.Fe();g.L(this.element,"ytp-autonav-cancelled-small-mode",this.yf(a));g.L(this.element,"ytp-autonav-cancelled-tiny-mode",this.Rw(a));g.L(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.dg(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Fe(1===c%2)}}};
g.k.fb=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=AHa(this,a))&&this.suggestions.length)for(this.i.Cs(this.suggestions[0]),this.i!==this.l&&this.l.Cs(this.suggestions[0]),a=0;a<FHa.length;++a){var b=FHa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new i3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,h3(c,b));g.H(this,this.videos[a]);this.videos[a].xa(this.J.element)}}this.Fe()}};
g.k.wE=function(a){1===a?(this.I=!1,this.u=this.videoData.clientPlaybackNonce,this.i.cm(),this.vb&&this.Fe()):(this.I=!0,this.Vd()&&(2===a?this.i.Pr():3===a&&this.i.Ap()))};
g.k.qM=function(a){a?this.wE(1):(this.u=null,this.I=!1)};
g.k.Ms=function(){return 1!==this.videoData.autonavState};
g.k.yf=function(a){return(910>a.width||459>a.height)&&!this.Rw(a)&&!(400>=a.width||360>=a.height)};
g.k.Rw=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Vd=function(){return this.vb&&g.ZL(this.player)&&this.Ms()&&!this.u};
var FHa=[1,3,2,4];g.u(t3,n3);t3.prototype.Ja=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Vg,author:a.author});this.subscribeButton.channelId=a.Vh;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.u(u3,g.V);u3.prototype.select=function(){(this.api.Mj(this.suggestion.bb().videoId,this.suggestion.ge,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.sA||void 0)||this.api.ea("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Kb(this.element)};
u3.prototype.onClick=function(a){g.AM(a,this.api,this.l,this.suggestion.ge||void 0)&&this.select()};
u3.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.hp(a)||(this.select(),g.gp(a))}};
u3.prototype.fb=function(){var a=this.api.getVideoData(),b=this.api.T();this.l=a.C?!1:b.l};g.u(v3,n3);g.k=v3.prototype;g.k.create=function(){n3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=BHa(this,a),this.videoData=a);this.Fe();this.l.N(this.player,"appresize",this.Fe);this.l.N(this.player,"onVideoAreaChange",this.Fe);this.l.N(this.player,"videodatachange",this.fb);this.l.N(this.player,"autonavchange",this.oz);this.l.N(this.player,"autonavcancel",this.rM);a=this.videoData.autonavState;a!==this.L&&this.oz(a);this.l.N(this.element,"transitionend",this.lS)};
g.k.destroy=function(){g.Xt(this.l);g.vi(this.stills);this.stills=[];this.suggestions=null;n3.prototype.destroy.call(this);g.jn(this.element,"ytp-show-tiles");this.I.stop();this.L=this.videoData.autonavState};
g.k.Ms=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){n3.prototype.show.call(this);g.jn(this.element,"ytp-show-tiles");this.player.T().i?this.I.eh():this.I.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.TL(this.player,!1);w3(this)?(x3(this),2===this.videoData.autonavState?this.player.T().ea("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Pr():3===this.videoData.autonavState&&this.i.Ap()):(g.TL(this.player,!0),x3(this))};
g.k.hide=function(){n3.prototype.hide.call(this);this.i.Ap();x3(this)};
g.k.lS=function(a){g.cp(a)===this.element&&this.Fe()};
g.k.Fe=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=this.G.Ck(!0,this.G.isFullscreen()),b=g.OL(this.G);b&&(b=b.df()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.sg(a,m,n);g.dg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Cs(this.suggestions[0]);this.i instanceof k3&&this.i.Fe();g.L(this.element,"ytp-endscreen-takeover",w3(this));x3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.$d(p+this.u,l),0!==r){t=this.stills[c];t||(t=new u3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,E=Math.floor(m*(f+r)/b)-x-4;g.lg(t.element,x,w);g.sg(t.element,E,y);g.dg(t.element,"transitionDelay",(h+f)/20+"s");g.L(t.element,"ytp-videowall-still-mini",1===r);g.L(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),w=g.gn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",h3(r,p,w),g.ED(t)&&(t=p.Vm(),t=g.Id(t,g.eN("emb_rel_end")),r.Oa("url",t)),(p=(p=p.ge)&&p.itct)&&r.api.In(r.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.He(e.element),g.ui(e);this.stills.length=c}};
g.k.fb=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=BHa(this,a),this.videoData=a,this.Fe())};
g.k.sM=function(){this.u+=this.stills.length;this.Fe()};
g.k.tM=function(){this.u-=this.stills.length;this.Fe()};
g.k.pH=function(){return this.i.Mh()};
g.k.oz=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.cm(),this.vb&&this.Fe()):(this.C=!0,this.vb&&w3(this)&&(2===a?this.i.Pr():3===a&&this.i.Ap()))};
g.k.rM=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.eb(this.stills[a].element,!0);this.oz(1)}else this.B=null,this.C=!1;this.Fe()};
g.k.Vd=function(){return this.vb&&w3(this)};g.u(y3,g.hM);g.k=y3.prototype;g.k.Jp=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!CHa(this.player)||b;var c=a.Pd||g.OD(a.B),d=this.player.wt();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Vd=function(){return this.endScreen.Vd()};
g.k.PO=function(){return this.Vd()?this.endScreen.pH():!1};
g.k.oa=function(){this.player.Df("endscreen");g.hM.prototype.oa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.dF;if(b&&b.videoId){var c=this.player.kb().Ed.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.ED?a=!1:(this.player.Mj(b.videoId,void 0,void 0,!0,!0,b),c&&c.Zw("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.hM.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.hM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Yd=function(a){this.Jp()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.ag=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.fb=function(){EHa(this);this.u&&DHa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new r3(this.player):this.endScreen=new v3(this.player),g.H(this,this.endScreen),g.YL(this.player,this.endScreen.element,4))};g.nM.endscreen=y3;})(_yt_player);
